version: "3"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: hico_demo_database
    restart: unless-stopped
    ports:
      - "6606:3306"
    environment:
      MYSQL_USER: hico_demo_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
      MYSQL_DATABASE: hico_demo
      